### ISSUE TITLE
Tertiary Destructive Button Loading 

### ISSUE THREAD

**Issue by jbelang** [ezcater/recipe#82] opened 2019-04-16 13:27 UTC
I noticed something a little weird with the loading state for the `destructive` button in Recipe. It appears to take on a red border that hugs the text and the spinner, resulting in a Chevy logo shape.

Here’s a screencap I grabbed of the behavior. Loading happens really fast, so the recorder didn’t catch it until the second attempt (around 10 seconds in):
http://recordit.co/Bia5Old4fs

I would expect that either there'd continue to be no border while the loading animation displayed, or that the border would be a normal rectangle.

**Comment by noranda** [comment] 2022-09-30 14:45
Closing issue. Cannot reproduce. See playroom example [here](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgNoA2EAhlAJZEDmANBhTFQBlmbTgF1sGAK58AylSZUYyAGZN6fNAG5ixUgCUYTMFQB00mAFFlymMdSZc%2BXaQytlGZAEJGLdh0wATvySAUTaRM6k5NQYVKwAtjABEnxUACoJMBCSVPbYeKlCvpwqaho8AKwADDVakRhBVCEk6Plk9IYBGYnZuXGJAXUkGAC%2BPAzCfqJDzo3NHvUAPBYAXgAKTBwwOPWkyysAQjlUECTmWAQgigFxTAEAnpcYsNQBksasAG4wGD4iHFhgH8-CMMKcAML0VhgADWgNajkKkxKVDeMDQIx2wxcLnBp2UrAC8QwABEYB04qddhhFgB6VZHKgnIhYnF01YbLasjBDEZodAjEAjIA).

**Closed by noranda** 2022-09-30 14:45 UTC
Labels: P3
