### ISSUE TITLE
Validation issues with browser autofill / password manager indicators on form fields

### ISSUE THREAD

**Issue by dave-ezcater** [ezcater/recipe#84] opened 2019-04-19 15:50 UTC
<img width="646" alt="Screen Shot 2019-04-19 at 11 07 25 AM" src="https://user-images.githubusercontent.com/39057183/56431840-3c23ac80-6299-11e9-9a8f-c45617622d08.png">

This is Chrome, autofill is competing for real estate with our form validation.

We should reconsider how we're handling form validation indicators.

**Comment by noranda** [comment] 2022-09-30 15:09
Closing issue. Cannot reproduce. Chrome autocomplete does not currently render an icon as far as I can tell. This may be a Chrome plugin, which we cannot and should not need to detect.

**Closed by noranda** 2022-09-30 15:09 UTC
Labels: P3
