### ISSUE TITLE
Add props for onChange events with EzCarousel

### ISSUE THREAD

**Issue by evan-007** [ezcater/recipe#694] opened 2021-08-26 18:16 UTC
We use EzCarousel in search for package m items:

<img width="1136" alt="Screen Shot 2021-08-26 at 2 11 01 PM" src="https://user-images.githubusercontent.com/5827130/131014262-18d126ad-124b-4cd8-89ef-53c3322a18f8.png">

We'd like to be able to measure interactions with the carousel, but there are no hooks into the click events for EzCarousel. 

**Describe the solution you'd like**

Something like like

```
<EzCarousel
  onClickNext={() => trackStuff()}
  onClickPrevious={() => trackStuff()}
```

I don't know if we'd have any use of info like the current displayed index, but maybe the callbacks could have the same shape as useCurrentPage? https://github.com/ezcater/recipe/blob/61bbe82a7c122af2496d351a4b2b5befd93917fe/src/components/EzCarousel/EzCarousel.tsx#L68

**Design Mockups**

N/A

**Comment by CraigCav** [comment] 2021-09-07 13:34
This looks like a duplicate of #683, which should be addressed by #690 when that lands.

**Closed by CraigCav** 2021-09-07 13:34 UTC
Labels: enhancement
